## Vector

In [1]:
import numpy as np

In [2]:
x = np.arange(4)
x

array([0, 1, 2, 3])

#### By default , vector can understood as vertical vector 

## Length, Dimension and Size

In [3]:
len(x)

4

In [4]:
x.shape

(4,)

In [5]:
x.size

4

## Matrix

In [6]:
# Create a 5x4 matrix:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
#Transpose  :
A.T # return a 4x5 matrix

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [8]:
#Note: With symmetry matrix A = A.T
B = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B ==B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Tensor

In [9]:
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
A = np.arange(20).reshape(5, 4)
B = A.copy()  # Assign a copy of A to B by allocating new memory
print(f' id(A): {id(A)}')
print(f'id(B): {id(B)}')
A, A + B

 id(A): 1476360470160
id(B): 1476360470240


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]]))

### Hadamard Product:

In [11]:
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [12]:
a = 2
X = np.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]]),
 (2, 3, 4))

In [13]:
x = np.arange(4)
x, x.sum()

(array([0, 1, 2, 3]), 6)

In [14]:
A.shape, A.sum()

((5, 4), 190)

In [15]:
A.sum(axis = 0), A.sum(axis = 0).shape # sum tensors by columns(sum each rows)

(array([40, 45, 50, 55]), (4,))

In [16]:
A.sum(axis = 1), A.sum(axis = 1).shape # sum tensors by rows(sum each columns)

(array([ 6, 22, 38, 54, 70]), (5,))

In [17]:
#Median values
print(A.mean())
A.mean() == A.sum()/A.size

9.5


True

In [18]:
# Median values each rows:
print(A.mean(axis = 0)) # Calculate by columns
print(A.mean(axis = 0) == A.sum(axis = 0)/ A.shape[0])

[ 8.  9. 10. 11.]
[ True  True  True  True]


In [20]:
#Keep dimensions:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [21]:
#Broadcasting:
A/sum_A

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])

In [22]:
#Cumulative Total:
A.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]], dtype=int32)

In [26]:
#Scalar:
y = np.ones(4)
x, y, np.dot(x, y), np.sum(x*y), x.shape,y.shape

(array([0, 1, 2, 3]), array([1., 1., 1., 1.]), 6.0, 6.0, (4,), (4,))

In [27]:
#Product matrix versus vector:
A.shape, x.shape, np.dot(A, x)

((5, 4), (4,), array([ 14,  38,  62,  86, 110]))

In [30]:
#Product matrix versus matrix:
B = np.ones(shape=(4, 3))
np.dot(A, B), A @B

(array([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]]),
 array([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]]))

In [31]:
#Norm l2:
u = np.array([3, -4])
np.linalg.norm(u)

5.0

In [32]:
#Norm l1:
np.abs(u).sum()

7

In [33]:
#Standard Frobenius:
np.linalg.norm(np.ones((4, 9)))

6.0