In [2]:
import numpy as np

## Create array in range

In [4]:
#Create array
np.arange(10, dtype = 'float64')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
#Random create array in normal standard and Gaussian standard
np.random.seed(42)
print(np.random.normal(0,1,size = (3,4)))
np.random.rand(3,4)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]


array([[0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378, 0.51423444]])

## Operator in element wise

In [18]:
#Example :
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x// y, x ** y  # The ** operator is exponentiation

(array([ 3,  4,  6, 10]),
 array([-1,  0,  2,  6]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([0, 1, 2, 4], dtype=int32),
 array([ 1,  4, 16, 64], dtype=int32))

## Concatenate nparray

In [24]:
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)
# axis = 0, concatenate by colums, axis = 1 concatenate by rows

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]]),
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]]))

## Sum all elements in a array 

In [4]:
x.sum()

66

## Broadcasting Mechanism

In [5]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0],
        [1],
        [2]]),
 array([[0, 1]]))

In [6]:
#Broadcasting 
# a: 3x1 matrix , b: 1x2 matrix => a+b will become 3x2 matrix
a+b

array([[0, 1],
       [1, 2],
       [2, 3]])

## Indexing and Splitting

In [12]:
print(f'{x[-1]} - last columns') # return last columns of matric X
x[1:3] # columns 1 to 2 columns

[ 8  9 10 11] - last columns


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Assign elements

In [15]:
x[1,2] = 9 # Assign one element
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]])

In [25]:
x[0:2, 0:2] = 12
x

array([[12, 12,  2,  3],
       [12, 12,  6,  7],
       [ 8,  9, 10, 11]])

## Save Memory

In [29]:
# Not change address of an element when update using Slice Notation(":")
z = np.zeros_like(y)
print('before: id(z):', id(z))
print('before: id(y):', id(y))
z[:] = x + y
y+=x
print('after: id(z):', id(z))
print('after: id(y):', id(y))


before: id(z): 2295816728080
before: id(y): 2295811534064
after: id(z): 2295816728080
after: id(y): 2295811534064
